"""Reference feature contracts and decision profiles for two location use cases."""

from youth_compass.decisioning.contracts import (
    ConstraintOperator,
    DecisionConstraint,
    DecisionCriterion,
    DecisionProfile,
    EntityType,
    FeatureDefinition,
    OptimizationDirection,
)

DEFAULT_FEATURES = (
    FeatureDefinition(
        feature_code="property_cost",
        display_name="Property cost",
        description="Median property or land cost per square metre.",
        entity_type=EntityType.LOCATION,
        unit_code="ntd_per_sqm",
        spatial_grain="location",
        temporal_grain="month",
        aggregation_method="median",
        source_metric_codes=("transaction_price_per_sqm", "listing_price_per_sqm"),
        tags=("housing", "land", "affordability"),
        valid_min=0,
    ),
    FeatureDefinition(
        feature_code="transit_accessibility",
        display_name="Transit accessibility",
        description="Normalized access to public transport from a location.",
        entity_type=EntityType.LOCATION,
        unit_code="score_0_100",
        spatial_grain="h3_9",
        temporal_grain="month",
        aggregation_method="weighted_score",
        source_metric_codes=("travel_time_to_transit", "nearby_transit_count"),
        tags=("mobility", "commute", "public_transport"),
        valid_min=0,
        valid_max=100,
    ),
    FeatureDefinition(
        feature_code="amenity_accessibility",
        display_name="Amenity accessibility",
        description="Normalized access to schools, healthcare, and daily services.",
        entity_type=EntityType.LOCATION,
        unit_code="score_0_100",
        spatial_grain="h3_9",
        temporal_grain="quarter",
        aggregation_method="weighted_score",
        source_metric_codes=("nearby_amenity_count",),
        tags=("amenity", "school", "healthcare"),
        valid_min=0,
        valid_max=100,
    ),
    FeatureDefinition(
        feature_code="environmental_risk",
        display_name="Environmental risk",
        description="Composite flood, air quality, noise, and hazard risk.",
        entity_type=EntityType.LOCATION,
        unit_code="score_0_100",
        spatial_grain="h3_9",
        temporal_grain="month",
        aggregation_method="weighted_score",
        source_metric_codes=("flood_risk", "air_quality_risk", "noise_risk"),
        tags=("environment", "flood", "air_quality", "noise"),
        valid_min=0,
        valid_max=100,
    ),
    FeatureDefinition(
        feature_code="ev_demand_proxy",
        display_name="EV demand proxy",
        description="Estimated charging demand derived from population, traffic, and EV ownership.",
        entity_type=EntityType.LOCATION,
        unit_code="score_0_100",
        spatial_grain="h3_9",
        temporal_grain="month",
        aggregation_method="model_score",
        source_metric_codes=("ev_ownership", "traffic_volume", "population_density"),
        tags=("ev", "charging", "demand"),
        valid_min=0,
        valid_max=100,
    ),
    FeatureDefinition(
        feature_code="parking_availability",
        display_name="Parking availability",
        description="Availability of usable parking spaces near a candidate location.",
        entity_type=EntityType.LOCATION,
        unit_code="score_0_100",
        spatial_grain="h3_9",
        temporal_grain="month",
        aggregation_method="weighted_score",
        source_metric_codes=("parking_space_count", "parking_occupancy"),
        tags=("parking", "site"),
        valid_min=0,
        valid_max=100,
    ),
    FeatureDefinition(
        feature_code="grid_accessibility",
        display_name="Grid accessibility",
        description="Suitability of nearby electrical capacity and connection distance.",
        entity_type=EntityType.LOCATION,
        unit_code="score_0_100",
        spatial_grain="site",
        temporal_grain="month",
        aggregation_method="weighted_score",
        source_metric_codes=("grid_capacity", "grid_connection_distance"),
        tags=("electricity", "grid", "site"),
        valid_min=0,
        valid_max=100,
    ),
    FeatureDefinition(
        feature_code="charger_competition",
        display_name="Charger competition",
        description="Existing public charging capacity relative to local demand.",
        entity_type=EntityType.LOCATION,
        unit_code="chargers_per_demand_index",
        spatial_grain="h3_9",
        temporal_grain="month",
        aggregation_method="ratio",
        source_metric_codes=("public_charger_count",),
        source_feature_codes=("ev_demand_proxy",),
        tags=("ev", "charging", "competition"),
        valid_min=0,
    ),
    FeatureDefinition(
        feature_code="site_feasibility",
        display_name="Site feasibility",
        description="Binary confirmation that zoning, area, and access constraints are satisfied.",
        entity_type=EntityType.LOCATION,
        unit_code="boolean_0_1",
        spatial_grain="site",
        temporal_grain="snapshot",
        aggregation_method="minimum",
        source_metric_codes=("zoning_allowed", "site_area_sufficient"),
        tags=("zoning", "site", "feasibility"),
        valid_min=0,
        valid_max=1,
    ),
)

DEFAULT_DECISION_PROFILES = (
    DecisionProfile(
        profile_code="home_buying",
        version="v1",
        display_name="Home buying location",
        candidate_type="residential_location",
        criteria=(
            DecisionCriterion(
                feature_code="property_cost",
                weight=0.35,
                direction=OptimizationDirection.MINIMIZE,
            ),
            DecisionCriterion(
                feature_code="transit_accessibility",
                weight=0.25,
                direction=OptimizationDirection.MAXIMIZE,
            ),
            DecisionCriterion(
                feature_code="amenity_accessibility",
                weight=0.20,
                direction=OptimizationDirection.MAXIMIZE,
            ),
            DecisionCriterion(
                feature_code="environmental_risk",
                weight=0.20,
                direction=OptimizationDirection.MINIMIZE,
            ),
        ),
    ),
    DecisionProfile(
        profile_code="ev_charger_placement",
        version="v1",
        display_name="EV charger placement",
        candidate_type="charger_site",
        criteria=(
            DecisionCriterion(
                feature_code="ev_demand_proxy",
                weight=0.35,
                direction=OptimizationDirection.MAXIMIZE,
            ),
            DecisionCriterion(
                feature_code="transit_accessibility",
                weight=0.10,
                direction=OptimizationDirection.MAXIMIZE,
                required=False,
            ),
            DecisionCriterion(
                feature_code="parking_availability",
                weight=0.20,
                direction=OptimizationDirection.MAXIMIZE,
            ),
            DecisionCriterion(
                feature_code="grid_accessibility",
                weight=0.25,
                direction=OptimizationDirection.MAXIMIZE,
            ),
            DecisionCriterion(
                feature_code="charger_competition",
                weight=0.10,
                direction=OptimizationDirection.MINIMIZE,
            ),
        ),
        constraints=(
            DecisionConstraint(
                feature_code="site_feasibility",
                operator=ConstraintOperator.GREATER_THAN_OR_EQUAL,
                threshold=1,
                reason="zoning, usable area, and site access must all be feasible",
            ),
        ),
    ),
)
