import { expect, test } from '@playwright/test'

test('a device motion restriction is visible and app-only consent enables every motion layer', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.spatial-dashboard')).toBeVisible({ timeout: 15000 })
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'reduced')
  await expect(page.locator('.chart-running-light')).toHaveCount(0)
  await page.getByRole('button', { name: '開啟儀表板動畫' }).click()
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'full')
  await expect(page.locator('html')).toHaveAttribute('data-motion-source', 'dashboard-consent')
  await expect(page.locator('.motion-preference-notice')).toHaveCount(0)
  await expect(page.getByTestId('chart-motion')).toHaveCount(10)
  expect(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(true)
  await expect(page.getByTestId('city-idle-layer')).toHaveCSS('animation-name', 'city-breathe')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'full')
  await expect(page.locator('.spatial-dashboard')).toBeVisible({ timeout: 15000 })
  if ((page.viewportSize()?.width ?? 0) < 1000) await page.getByRole('button', { name: '開啟導覽選單' }).click()
  await page.getByRole('link', { name: /人口趨勢/ }).click()
  await page.waitForTimeout(350)
  await expect(page.getByTestId('section-scroll-progress')).toHaveAttribute('data-active', 'true')
  await expect(page.getByTestId('section-scroll-progress')).toHaveAttribute('data-active', 'false', { timeout: 4500 })
  await page.mouse.move(5, 5)
  const plot = page.locator('#population-trend .chart-motion')
  await expect(plot).toHaveAttribute('data-motion-state', 'complete')
  await page.getByRole('button', { name: '重播繪製動畫', exact: true }).click()
  await expect(plot).toHaveAttribute('data-motion-state', 'drawing')
  const mask = plot.locator('.chart-reveal-mask rect')
  const before = await mask.evaluate(el => getComputedStyle(el).transform)
  await page.waitForTimeout(250)
  expect(await mask.evaluate(el => getComputedStyle(el).transform)).not.toBe(before)
  await page.goto('/?motion=system')
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'reduced')
})

test('the motion link works with native browser preferences, not a forced test preference', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: null })
  await page.goto('/?motion=full')
  await expect(page.locator('.spatial-dashboard')).toBeVisible({ timeout: 15000 })
  const nativePreference = await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'full')
  await expect(page.getByTestId('city-idle-layer')).toHaveCSS('animation-name', 'city-breathe')
  await page.goto('/')
  await expect(page.locator('.spatial-dashboard')).toBeVisible({ timeout: 15000 })
  await expect(page.locator('html')).toHaveAttribute('data-motion', 'full')
  expect(await page.evaluate(() => matchMedia('(prefers-reduced-motion: reduce)').matches)).toBe(nativePreference)
  await page.mouse.move(5, 5)
  const before = await page.getByTestId('city-idle-layer').evaluate(el => getComputedStyle(el).transform)
  await page.waitForTimeout(350)
  expect(await page.getByTestId('city-idle-layer').evaluate(el => getComputedStyle(el).transform)).not.toBe(before)
})
