import { expect, test } from '@playwright/test'

test('a blank line draws to its real value once, with stationary text and no looping highlight', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const motion = page.locator('#population-trend .chart-motion')
  await expect(motion).toHaveAttribute('data-motion-state', 'waiting', { timeout: 15000 })
  await expect(motion.locator('.recharts-area-curve')).toHaveCSS('visibility', 'hidden')
  await page.locator('#population-trend').evaluate(el => window.scrollTo(0, el.getBoundingClientRect().top + scrollY - 100))
  await expect(motion).toHaveAttribute('data-motion-state', 'drawing')
  const mask = motion.locator('.chart-reveal-mask rect')
  const initial = await mask.evaluate(el => {
    const animation = el.getAnimations()[0]
    animation.pause(); animation.currentTime = 0
    return new DOMMatrix(getComputedStyle(el).transform).a
  })
  expect(initial).toBe(0)
  const paths = await motion.locator('.recharts-area-curve').getAttribute('d')
  const ticks = await motion.locator('.recharts-cartesian-axis-ticks').allTextContents()
  await mask.evaluate(el => { el.getAnimations()[0].currentTime = 1200 })
  const middle = await mask.evaluate(el => new DOMMatrix(getComputedStyle(el).transform).a)
  expect(middle).toBeCloseTo(0.5, 1)
  expect(await motion.locator('.recharts-area-curve').getAttribute('d')).toBe(paths)
  expect(await motion.locator('.recharts-cartesian-axis-ticks').allTextContents()).toEqual(ticks)
  await mask.evaluate(el => { el.getAnimations()[0].play() })
  await expect(motion).toHaveAttribute('data-motion-state', 'complete')
  await expect(motion.locator('.recharts-area-curve')).toHaveCSS('clip-path', 'none')
  await expect(page.locator('.chart-running-light')).toHaveCount(0)
  const count = await motion.getAttribute('data-reveal-count')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.locator('#population-trend').evaluate(el => window.scrollTo(0, el.getBoundingClientRect().top + scrollY - 100))
  expect(await motion.getAttribute('data-reveal-count')).toBe(count)
  await page.getByRole('button', { name: '重播繪製動畫', exact: true }).click()
  await expect(motion).toHaveAttribute('data-motion-state', 'drawing')
  await expect(motion).toHaveAttribute('data-reveal-count', String(Number(count) + 1))
  await expect(page.locator('#population-trend .chart-end-value')).toContainText('青年')
})

test('data changes restart the plot, while reduced motion shows all data immediately', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const motion = page.locator('#age-structure .chart-motion')
  await expect(motion).toHaveAttribute('data-motion-state', 'waiting', { timeout: 15000 })
  await page.locator('#age-structure').evaluate(el => window.scrollTo(0, el.getBoundingClientRect().top + scrollY - 100))
  await expect(motion).toHaveAttribute('data-reveal-count', '1')
  await expect(motion).toHaveAttribute('data-motion-state', 'complete')
  await page.getByLabel('資料年份', { exact: true }).click()
  await page.getByRole('option', { name: /^2025/ }).click()
  await page.locator('#age-structure').evaluate(el => window.scrollTo(0, el.getBoundingClientRect().top + scrollY - 100))
  await expect(motion).toHaveAttribute('data-reveal-count', '2')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(motion).toHaveAttribute('data-motion-state', 'reduced')
  await expect(motion.locator('.recharts-rectangle').first()).toHaveCSS('clip-path', 'none')
  await expect(motion.locator('.recharts-rectangle').first()).toHaveCSS('visibility', 'visible')
  await expect(page.locator('.chart-reveal-mask')).toHaveCount(0)
})

test('text stays idle while only the illustrative 3D city moves', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const city = page.getByTestId('city-idle-layer')
  await expect(city).toBeVisible({ timeout: 15000 })
  await page.mouse.move(5, 5)
  const before = await city.evaluate(el => getComputedStyle(el).transform)
  const title = page.locator('.hero-title')
  const first = await title.boundingBox()
  await page.waitForTimeout(450)
  expect(await title.boundingBox()).toEqual(first)
  expect(await city.evaluate(el => getComputedStyle(el).transform)).not.toBe(before)
  await expect(page.locator('.float-bob').first()).toHaveCSS('animation-name', 'none')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(city).toHaveCSS('transform', 'none')
})
