import { expect, test } from '@playwright/test'

test('wheel and sidebar keep smooth travel without moving or bending text', async ({ page }) => {
  test.skip((page.viewportSize()?.width ?? 0) < 1000, 'Desktop wheel and sidebar input')
  await page.emulateMedia({ reducedMotion: 'no-preference' })
  await page.goto('/')
  const title = page.locator('.hero-editorial > .float-shell').nth(1)
  await expect(title).toHaveAttribute('data-in-view', 'true', { timeout: 15000 })
  const bob = title.locator('.float-bob')
  const firstIdle = await bob.evaluate(el => getComputedStyle(el).transform)
  await page.waitForTimeout(350)
  expect(await bob.evaluate(el => getComputedStyle(el).transform)).toBe(firstIdle)

  await page.mouse.move(1300, 90)
  await page.mouse.wheel(0, 650)
  await page.waitForTimeout(160)
  const early = await page.evaluate(() => scrollY)
  expect(early).toBeGreaterThan(10)
  expect(early).toBeLessThan(620)
  const moving = await page.locator('[data-in-view="true"] > .float-motion').evaluateAll(elements =>
    elements.some(el => Math.abs(new DOMMatrix(getComputedStyle(el).transform).m42) > 2))
  expect(moving).toBe(false)
  await page.waitForTimeout(280)
  expect(await page.evaluate(() => scrollY)).toBeGreaterThan(early + 20)

  await page.getByRole('link', { name: /district profile/i }).click()
  await page.waitForTimeout(550)
  await expect(page.getByTestId('section-scroll-progress')).toHaveAttribute('data-active', 'true')
  const bending = await page.locator('[data-in-view="true"] > .float-motion').evaluateAll(elements =>
    elements.some(el => Math.abs(new DOMMatrix(getComputedStyle(el).transform).m12) > 0.001))
  expect(bending).toBe(false)
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(page.locator('.float-bob').first()).toHaveCSS('animation-name', 'none')
  await expect(page.getByTestId('velocity-surface').first()).toHaveCSS('transform', 'none')
})

test('map and proportional 3D blocks use the CSV year and district selection', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.getByTestId('district-map')).toBeVisible({ timeout: 15000 })
  const districts = page.locator('.map-district')
  await expect(districts).toHaveCount(29)
  const banqiao = page.getByRole('button', { name: /^選擇板橋區，/ })
  await banqiao.focus()
  await page.keyboard.press('Enter')
  await expect(banqiao).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('combobox', { name: '行政區', exact: true })).toContainText('板橋區')
  await expect(page.locator('#age-structure')).toContainText('板橋區')
  const year2026 = await banqiao.getAttribute('aria-label')
  await page.getByRole('combobox', { name: '資料年份', exact: true }).click()
  await page.getByRole('option', { name: /^2025/ }).click()
  await expect(banqiao).not.toHaveAttribute('aria-label', year2026!)
  await expect(page.getByRole('group', { name: /New Taipei district map/ })).toHaveAttribute('aria-label', /2025/)
  const largest = await page.locator('.city-block').evaluateAll(blocks => blocks.map(block => ({
    value: Number(block.getAttribute('data-population')),
    height: parseFloat((block as HTMLElement).style.getPropertyValue('--block-height')),
  })).sort((a, b) => b.value - a.value))
  expect(largest).toHaveLength(29)
  expect(largest[0].height).toBeCloseTo(80, 3)
  expect(largest[28].height / largest[0].height).toBeCloseTo(largest[28].value / largest[0].value, 5)
  await expect(page.locator('.district-map-svg')).toHaveClass(/is-raised/)
  await expect(page.getByRole('button', { name: 'Flat map', exact: true })).toHaveCount(0)
  await expect(page.getByTestId('district-stats')).toContainText('板橋區')
  await expect(page.locator('.district-ranking')).toHaveCount(0)
  await page.getByRole('button', { name: '清除行政區選擇' }).click()
  await expect(page.getByRole('combobox', { name: '行政區', exact: true })).toContainText('全市')
  await expect(page.locator('.map-district[aria-pressed="true"]')).toHaveCount(0)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})

test('open surfaces and filter menus fit a narrow 320px screen', async ({ page }) => {
  test.skip((page.viewportSize()?.width ?? 0) > 1000, 'Small-screen regression')
  await page.setViewportSize({ width: 320, height: 700 })
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  await expect(page.locator('.spatial-dashboard')).toBeVisible({ timeout: 15000 })
  await expect(page.locator('#overview')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  await expect(page.locator('#population-trend')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)')
  for (const label of ['行政區', '資料年份']) {
    await page.getByLabel(label, { exact: true }).click()
    const box = await page.locator('.filter-menu-portal').boundingBox()
    expect(box!.x).toBeGreaterThanOrEqual(0)
    expect(box!.x + box!.width).toBeLessThanOrEqual(320)
    expect(box!.y).toBeGreaterThanOrEqual(0)
    expect(box!.y + box!.height).toBeLessThanOrEqual(700)
    await page.keyboard.press('Escape')
  }
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})
