import { chromium } from '@playwright/test'
import { mkdir } from 'node:fs/promises'

await mkdir('designs/spatial-review', { recursive: true })
const browser = await chromium.launch({ channel: 'msedge', headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 1000 }, colorScheme: 'light', reducedMotion: 'no-preference' })
const errors = []
page.on('pageerror', error => errors.push(error.message))
await page.goto('http://127.0.0.1:5173')
await page.locator('.spatial-dashboard').waitFor()
await page.waitForTimeout(1200)
await page.screenshot({ path: 'designs/spatial-review/desktop-light.png' })
await page.evaluate(() => {
  window.spatialSamples = []
  const start = performance.now()
  function sample(now) {
    const surfaces = [...document.querySelectorAll('[data-in-view="true"] > .float-motion')]
    window.spatialSamples.push({ ms: Math.round(now - start), y: scrollY, transforms: surfaces.slice(0, 2).map(el => el.style.transform) })
    if (now - start < 2500) requestAnimationFrame(sample)
  }
  requestAnimationFrame(sample)
})
await page.getByRole('link', { name: /district profile/i }).click()
await page.waitForTimeout(2850)
console.log('Sidebar velocity samples', await page.evaluate(() => window.spatialSamples.filter((_, index) => index % 20 === 0)))
await page.screenshot({ path: 'designs/spatial-review/district-map-light.png' })
await page.getByRole('button', { name: 'Use dark theme' }).click()
await page.waitForTimeout(400)
await page.screenshot({ path: 'designs/spatial-review/district-map-dark.png' })
console.log('Map controls', await page.locator('.map-district').count())
console.log('Desktop overflow', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth))
await page.getByRole('link', { name: /overview/i }).click()
await page.waitForTimeout(2850)
await page.screenshot({ path: 'designs/spatial-review/desktop-dark.png' })
await page.mouse.move(1100, 100)
await page.mouse.wheel(0, 700)
await page.waitForTimeout(180)
const early = await page.evaluate(() => scrollY)
await page.waitForTimeout(350)
console.log('Wheel coast', { early, later: await page.evaluate(() => scrollY) })
await page.setViewportSize({ width: 390, height: 844 })
await page.emulateMedia({ reducedMotion: 'reduce' })
await page.evaluate(() => scrollTo(0, 0))
await page.waitForTimeout(1000)
await page.screenshot({ path: 'designs/spatial-review/mobile-dark.png' })
await page.screenshot({ path: 'designs/spatial-review/mobile-page.png', fullPage: true })
console.log('Mobile overflow', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth))
await page.emulateMedia({ reducedMotion: 'no-preference' })
await page.locator('#district-profile').scrollIntoViewIfNeeded()
await page.waitForTimeout(600)
await page.screenshot({ path: 'designs/spatial-review/mobile-map.png' })
await page.setViewportSize({ width: 320, height: 700 })
await page.waitForTimeout(500)
console.log('320px overflow', await page.evaluate(() => document.documentElement.scrollWidth - innerWidth))
console.log('Runtime errors', errors)
const localhost = await browser.newPage()
await localhost.goto('http://localhost:5173')
await localhost.locator('.spatial-dashboard').waitFor({ timeout: 10000 })
console.log('localhost:5173 also serves the updated spatial dashboard')
await browser.close()
