"""Regenerate the frontend's canonical district dictionary.

The frontend must resolve backend entity identifiers to map areas. The atlas
ships a ``number`` field that is alphabetical by English name (Bali = 1,
Banqiao = 2 ...), which is NOT the backend district code (板橋區 = 01,
三重區 = 02 ...). Joining on it silently mislabels every district, so the
dictionary is generated from ``youth_compass.mapping.geography`` and the atlas
is joined by name only.

Run after changing the district dictionary or swapping the atlas:

    uv run python -m scripts.generate_district_dictionary
"""

import json
from pathlib import Path

from youth_compass.mapping.geography import DISTRICTS

_ROOT = Path(__file__).resolve().parents[1]
_ATLAS = _ROOT / "frontend" / "src" / "data" / "district-map.json"
_OUTPUT = _ROOT / "frontend" / "src" / "lib" / "districts.ts"

_HEADER = """/** Canonical New Taipei district dictionary.
 *
 * GENERATED by scripts/generate_district_dictionary.py from
 * src/youth_compass/mapping/geography.py and the English names in
 * src/data/district-map.json. Do not hand-edit.
 *
 * The atlas ships its own `number` field, which is alphabetical by English name
 * (Bali = 1, Banqiao = 2 ...). That is NOT the backend's district code
 * (板橋區 = 01, 三重區 = 02 ...). Joining on it silently mislabels every district,
 * so nothing here reads `number` — the join key is the name or the code.
 */

export type District = { code: string; name: string; english: string }

export const DISTRICTS: readonly District[] = [
"""

_FOOTER = """]

const byCode = new Map(DISTRICTS.map(d => [d.code, d]))
const byName = new Map(DISTRICTS.map(d => [d.name, d]))
const byEnglish = new Map(DISTRICTS.map(d => [d.english.toLowerCase(), d]))

/** Resolve one backend entity identifier to a district, or null.
 *
 * Exact matches only, across the three shapes the backend actually emits:
 * a zero-padded code ('01'), a canonical Chinese name ('板橋區'), or a lowercase
 * English slug ('banqiao'). Anything else — a site, a grid cell, a name this
 * dictionary does not contain — returns null and is reported as unplaceable.
 * Fuzzy or substring matching is deliberately absent: guessing that
 * 'site-banqiao-station' sits in 板橋區 would be an unfounded spatial join. */
export function resolveDistrict(value: string | null | undefined): District | null {
  if (!value) return null
  const raw = value.trim()
  if (!raw) return null

  const padded = /^\\d{1,2}$/.test(raw) ? raw.padStart(2, '0') : raw
  const byCodeHit = byCode.get(padded)
  if (byCodeHit) return byCodeHit

  const named = byName.get(raw) ?? byName.get(raw.endsWith('區') ? raw : `${raw}區`)
  if (named) return named

  return byEnglish.get(raw.toLowerCase()) ?? null
}
"""


def build() -> str:
    """Render the dictionary module, failing loudly on any atlas mismatch."""

    atlas = json.loads(_ATLAS.read_text(encoding="utf-8"))
    english_by_name = {
        area["name"]: area["english"].removesuffix(" District") for area in atlas["districts"]
    }
    known = {district.name for district in DISTRICTS}
    missing = sorted(known - set(english_by_name))
    if missing:
        raise SystemExit(f"atlas is missing districts the backend knows: {missing}")
    extra = sorted(set(english_by_name) - known)
    if extra:
        raise SystemExit(f"atlas has districts the backend does not know: {extra}")

    rows = "".join(
        f"  {{ code: '{district.code}', name: '{district.name}', "
        f"english: '{english_by_name[district.name]}' }},\n"
        for district in DISTRICTS
    )
    return f"{_HEADER}{rows}{_FOOTER}"


def main() -> None:
    _OUTPUT.write_text(build(), encoding="utf-8")
    print(f"wrote {len(DISTRICTS)} districts to {_OUTPUT.relative_to(_ROOT)}")


if __name__ == "__main__":
    main()
