/** Canonical New Taipei district dictionary.
 *
 * GENERATED by scripts/generate_district_dictionary.py from
 * src/youth_compass/mapping/geography.py and the English names in
 * src/data/district-map.json. Do not hand-edit.
 *
 * The atlas ships its own `number` field, which is alphabetical by English name
 * (Bali = 1, Banqiao = 2 ...). That is NOT the backend's district code
 * (板橋區 = 01, 三重區 = 02 ...). Joining on it silently mislabels every district,
 * so nothing here reads `number` — the join key is the name or the code.
 */

export type District = { code: string; name: string; english: string }

export const DISTRICTS: readonly District[] = [
  { code: '01', name: '板橋區', english: 'Banqiao' },
  { code: '02', name: '三重區', english: 'Sanchong' },
  { code: '03', name: '中和區', english: 'Zhonghe' },
  { code: '04', name: '永和區', english: 'Yonghe' },
  { code: '05', name: '新莊區', english: 'Xinzhuang' },
  { code: '06', name: '新店區', english: 'Xindian' },
  { code: '07', name: '土城區', english: 'Tucheng' },
  { code: '08', name: '蘆洲區', english: 'Luzhou' },
  { code: '09', name: '樹林區', english: 'Shulin' },
  { code: '10', name: '鶯歌區', english: 'Yingge' },
  { code: '11', name: '三峽區', english: 'Sanxia' },
  { code: '12', name: '淡水區', english: 'Tamsui' },
  { code: '13', name: '汐止區', english: 'Xizhi' },
  { code: '14', name: '瑞芳區', english: 'Ruifang' },
  { code: '15', name: '五股區', english: 'Wugu' },
  { code: '16', name: '泰山區', english: 'Taishan' },
  { code: '17', name: '林口區', english: 'Linkou' },
  { code: '18', name: '八里區', english: 'Bali' },
  { code: '19', name: '深坑區', english: 'Shenkeng' },
  { code: '20', name: '石碇區', english: 'Shiding' },
  { code: '21', name: '坪林區', english: 'Pinglin' },
  { code: '22', name: '三芝區', english: 'Sanzhi' },
  { code: '23', name: '石門區', english: 'Shimen' },
  { code: '24', name: '金山區', english: 'Jinshan' },
  { code: '25', name: '萬里區', english: 'Wanli' },
  { code: '26', name: '平溪區', english: 'Pingxi' },
  { code: '27', name: '雙溪區', english: 'Shuangxi' },
  { code: '28', name: '貢寮區', english: 'Gongliao' },
  { code: '29', name: '烏來區', english: 'Wulai' },
]

const byCode = new Map(DISTRICTS.map(d => [d.code, d]))
const byName = new Map(DISTRICTS.map(d => [d.name, d]))
const byEnglish = new Map(DISTRICTS.map(d => [d.english.toLowerCase(), d]))

/** Resolve one backend entity identifier to a district, or null.
 *
 * Exact matches only, across the three shapes the backend actually emits:
 * a zero-padded code ('01'), a canonical Chinese name ('板橋區'), or a lowercase
 * English slug ('banqiao'). Anything else — a site, a grid cell, a name this
 * dictionary does not contain — returns null and is reported as unplaceable.
 * Fuzzy or substring matching is deliberately absent: guessing that
 * 'site-banqiao-station' sits in 板橋區 would be an unfounded spatial join. */
export function resolveDistrict(value: string | null | undefined): District | null {
  if (!value) return null
  const raw = value.trim()
  if (!raw) return null

  const padded = /^\d{1,2}$/.test(raw) ? raw.padStart(2, '0') : raw
  const byCodeHit = byCode.get(padded)
  if (byCodeHit) return byCodeHit

  const named = byName.get(raw) ?? byName.get(raw.endsWith('區') ? raw : `${raw}區`)
  if (named) return named

  return byEnglish.get(raw.toLowerCase()) ?? null
}
